### ISSUE TITLE
I wonder if It would be a Cassandra impl?

### ISSUE THREAD

**Issue by antoniochievaro** [javiorfo/nvim-tabula#1]
Hello,
I currently use this plugin with MongoDB and it works perfectly. Great work here!!
I would like this plugin to work with Cassandra in the future.
Thanks, Javier!!

**Comment by javiorfo** [comment]
Hello,
At the time of writing this response Cassandra is not considered to be implemented.
In the future I don't know.
Thanks for your comments!
